name: org_flutter
description: Flutter widgets for displaying Emacs Org Mode (https://orgmode.org) content
version: 4.1.1
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.14.0-0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_tex_js: ^2.0.0
  # flutter_tex_js:
  #   path: ../flutter_tex_js
  highlight: ^0.7.0
  org_parser: ^5.0.0
  # org_parser:
    # path: ../org_parser

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
