name: org_flutter
description: Flutter widgets for displaying Emacs Org Mode (https://orgmode.org) content
version: 1.4.2
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.14.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_tex_js: ^1.0.0
  # flutter_tex_js:
  #   path: ../flutter_tex_js
  highlight: ^0.7.0
  org_parser: ^2.2.0
  # org_parser:
    # path: ../org_parser

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
