name: org_flutter
description: Org-mode widgets for Flutter
version: 0.1.1
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  org_parser: ^0.1.0
#  org_parser:
#    path: ../org_parser

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
