name: org_flutter
description: Flutter widgets for displaying Emacs Org Mode (https://orgmode.org) content
version: 6.0.1
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.14.0-0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_highlighting not needed until pending issues addressed upstream; see
  # highlight.dart
  # flutter_highlighting: ^0.9.0+11.8.0
  flutter_slidable: ^3.0.1
  flutter_tex_js: ^3.0.0
  # flutter_tex_js:
  #   path: ../flutter_tex_js/flutter_tex_js
  highlighting: ^0.9.0+11.8.0
  org_parser: ^5.6.0
  # org_parser:
    # path: ../org_parser
  petitparser: ^6.0.1
  petit_lisp: ">=6.4.0 <6.5.0"
  # petit_lisp:
    # path: ../petit_lisp

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
