name: org_flutter
description: Flutter widgets for displaying Emacs org-mode (https://orgmode.org) content
version: 0.5.0
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  org_parser: ^0.2.0
  # org_parser:
  #   path: ../org_parser
  flutter_highlight: ^0.6.0
  highlight: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
