name: org_flutter
description: Flutter widgets for displaying Emacs Org Mode (https://orgmode.org) content
version: 9.9.0
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0-0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_highlighting not needed until pending issues addressed upstream; see
  # highlight.dart
  # flutter_highlighting: ^0.9.0+11.8.0
  flutter_slidable: ^4.0.0
  flutter_tex_js: ^5.0.0
  # flutter_tex_js:
  #   path: ../flutter_tex_js/flutter_tex_js
  highlighting: ^0.9.0+11.8.0
  org_parser: ^9.10.0
  # org_parser:
    # path: ../org_parser
  petitparser: ^7.0.1
  petit_lisp: ^6.5.0
  # petit_lisp:
    # path: ../petit_lisp
  more: ^4.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
