name: org_flutter
description: Flutter widgets for displaying Emacs org-mode (https://orgmode.org) content
version: 0.4.1
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  org_parser: ^0.1.0
#  org_parser:
#    path: ../org_parser

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
