name: org_flutter
description: Flutter widgets for displaying Emacs org-mode (https://orgmode.org) content
version: 0.9.0
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  flutter_tex_js: ^0.1.0
  # flutter_tex_js:
  #   path: ../flutter_tex_js
  highlight: ^0.6.0
  org_parser: ^0.5.0
  # org_parser:
  #   path: ../org_parser

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
